accepted = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Unlicense",
  "BSD-3-Clause",
  "CC0-1.0",
  "MIT-0",
  "Zlib",
  "Unicode-3.0",
  "bzip2-1.0.6",
  "LGPL-2.1-or-later"
]

[zstd-sys.clarify]
# Dieses Crate benötigt BEIDE Lizenzen (AND)
license = "MIT AND BSD-3-Clause"

# 1. MIT-Lizenz (Rust-Wrapper)
[[zstd-sys.clarify.files]]
path = "LICENSE.Mit"
license = "MIT"
checksum = "129e8edef29e9abcd2ebabe252f4ef1b1289cdca356bf0040284a2fbccfb96c8"

# 2. Der Beweis für die BSD-Lizenz (Zstandard C-Code von Meta)
[[zstd-sys.clarify.files]]
path = "LICENSE.BSD-3-Clause"
license = "BSD-3-Clause"
checksum = "48341f685c87304089aa099b23c386f8bacc519ef555aa7a13e239908907b3fd"